### ISSUE TITLE
Gitter Chat for Progeny is possibly incorrect.

### ISSUE THREAD

**Issue by shymega** [darthlukan/progeny#17]
The Gitter chat topic for Progeny states that Progeny is 'A project generator written in Go and inspired by tools like Yeoman', however I was under the impression Progeny was written in Python.

Furthermore, I cannot see any Go code in the repo, which possibly indicates that the Gitter Topic is incorrect.

**Comment by darthlukan** [comment]
This is an issue with Gitter, not with Progeny. The Gitter channel information did not update when I updated the description in Github and apparently, there's no button for me to change it in Gitter.

**Comment by darthlukan** [comment]
Nevermind, double-clicking the topic allows editing. Fixed.
